vortex:
  #苏州云平台
  rest.url:
    #坐标偏转服务（坐标偏转，获取地址，点到点/线/面距离计算）
    lbs: ${gatewayServer}
    #文件管理服务（文件上传，下载）
    file: ${gatewayServer}
    #后台管理服务(1.0叫management，1.1叫ums)
    ums: ${gatewayServer}
    #APP管理服务（APP版本管理，APP极光推送）
    app: ${gatewayServer}
    #视频管理服务
    vis: ${gatewayServer}
    #车辆维修服务
    clwx: ${gatewayServer}
    #排班管理服务
    pbgl: ${gatewayServer}
    #车辆定位服务
    gps: ${gatewayServer}
    #基础设施服务-http://117.149.227.62:8003
    jcss: ${gatewayServer}
    #作业考核服务（1.1版本）
    zykh: ${gatewayServer}
    #作业清扫服务（1.0版本，排班管理用的到）
    zyqs-v1: ${gatewayServer}
    #作业清扫服务（1.1版本）
    zyqs: ${gatewayServer}
    #作业人员服务（1.1版本）
    zyry: ${gatewayServer}
    #终端考评服务
    zdkp: ${gatewayServer}
    #终端监管-http://116.62.100.64:7004
    zdjg: ${gatewayServer}
    #审批流程服务
    splc: ${gatewayServer}
  #杭州云平台
  env.url:
    #读卡器-CLWX
    obd: http://lan.envcloud.com.cn:7610
    #报警服务-GPS,ZYQS用到
    ans: http://api.envcloud.com.cn:9010
    #简单数据服务-JCSS用到
    sds: http://api.envcloud.com.cn:9011
    #设备管理服务-ZYRY用到
    dms: http://api.envcloud.com.cn:9012
    #称重数据服务-ZDJG用到
    weigh-data: http://api.envcloud.com.cn:9021
    #车辆数据服务-GPS用到
    vehicle-data: http://api.envcloud.com.cn:9022
    #一体机数据服务-CLWXFW用到
    ytj-data: http://110.87.96.19:9022
    #设备消息发送服务-ZYRY用到
    cmd-send: http://api.envcloud.com.cn:9026
    #佩琪一代数据服务-ZYRY用到
    xm-data: http://api.envcloud.com.cn:9028
    #人员数据查询服务-ZYRY用到
    staff-data-read: http://api.envcloud.com.cn:9029
    #kelong数据服务-JCSS用到
    kl-data: http://api.envcloud.com.cn:9038
    #佩琦二代数据服务-ZYRY用到
    peiqi-data: http://api.envcloud.com.cn:10102
    #油水查询配置-JCSS用到
    device-config: http://api.envcloud.com.cn:20002
    #车辆油耗数据服务-GPS用到
    vehicle-oil: http://api.envcloud.com.cn:20003
    #设备升级服务-CLWX用到
    device-upgrade: http://api.envcloud.com.cn:20005
    #808数据服务-GPS用到
    bb808-data: http://api.envcloud.com.cn:25210